apiVersion: v1
kind: ServiceAccount
metadata:
   name: aws-cli-sa
   namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec: 
  serviceAccountName: aws-cli-sa
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["sleep","infinity"]